services:
  web:
    image: nginx:alpine
    #ports:
    #  - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - nginxmanager_default
    restart: always

networks:
  nginxmanager_default:
    external: true
